import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/tokens.css',
                'resources/css/components.css',
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/css/website.css',
                'resources/css/website-base.css',
                'resources/css/website-home.css',
                'resources/css/website-home-entry.css',
                'resources/css/website-home-mobile.css',
                'resources/css/website-home-critical.css',
                'resources/css/website-home-deferred.css',
                'resources/css/website-after.css',
                'resources/css/website-theme.css',
                'resources/css/website-rtl.css',
                'resources/css/website-header.css',
                'resources/css/egypt-tour-pro-final.css',
                'resources/js/website.js',
                // Page-specific styles
                'resources/css/pages/attractions-by-city.css',
                'resources/css/pages/attractions-index.css',
                'resources/css/pages/attractions-show.css',
                'resources/css/pages/blogs-index.css',
                'resources/css/pages/blogs-show.css',
                'resources/css/pages/checkout-show.css',
                'resources/css/pages/checkout-status.css',
                'resources/css/pages/contact-us.css',
                'resources/css/pages/day-tours-index.css',
                'resources/css/pages/destinations-index.css',
                'resources/css/pages/destinations-show.css',
                'resources/css/pages/enquiry-form.css',
                'resources/css/pages/multi-country.css',
                'resources/css/pages/nile-cruise-details.css',
                'resources/css/pages/nile-cruise-pricing.css',
                'resources/css/pages/nile-cruises-index.css',
                'resources/css/pages/nile-cruises-listing.css',
                'resources/css/pages/nile-cruises-luxor-aswan.css',
                'resources/css/pages/offers.css',
                'resources/css/pages/packages-index.css',
                'resources/css/pages/packages-show.css',
                'resources/css/pages/search.css',
                'resources/css/pages/static-pages-index.css',
                'resources/css/pages/tailor-made.css',
                'resources/css/pages/travel-packages-index.css',
                'resources/css/pages/travel-tips.css',
                // Page-specific scripts
                'resources/js/pages/blogs-index.js',
                'resources/js/pages/blogs-show.js',
                'resources/js/pages/checkout-show.js',
                'resources/js/pages/contact-us.js',
                'resources/js/pages/destinations-index.js',
                'resources/js/pages/enquiry-form.js',
                'resources/js/pages/nile-cruise-details.js',
                'resources/js/pages/packages-show.js',
                'resources/js/pages/search.js',
                'resources/js/pages/tailor-made.js',
                'resources/js/pages/travel-tips.js',
            ],
            refresh: true,
        }),
    ],
    build: {
        cssCodeSplit: true,
        minify: 'esbuild',
        sourcemap: false,
        target: 'es2020',
        assetsInlineLimit: 0,
        rollupOptions: {
            output: {
                entryFileNames: 'assets/[name]-[hash].js',
                chunkFileNames: 'assets/[name]-[hash].js',
                assetFileNames: 'assets/[name]-[hash][extname]',
            },
        },
    },
});
